# Your MySQL server information

drivername="mysql+pymysql"
username = "admin"
password = "DB_read81"
host = "semester-1-project.c3quok406kii.eu-north-1.rds.amazonaws.com"
port = 3306
database_name = "cosmetics_db"

table = "cosmetics"